# Generated by Django 6.0 on 2025-12-11 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ladders",
            fields=[
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("budget", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "cap",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "cover",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("direction", models.CharField(blank=True, max_length=10, null=True)),
                ("enable", models.BooleanField(default=False, null=True)),
                (
                    "gap",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "highest",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "last",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("lcd", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "limit_price_in_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "lowest",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("market", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "profit_per_trade",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "shares_per_trade",
                    models.DecimalField(
                        blank=True, decimal_places=16, max_digits=16, null=True
                    ),
                ),
                (
                    "stop_price_in_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "symbol_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("symbol", models.CharField(blank=True, max_length=10, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Steps",
            fields=[
                ("step_code", models.CharField(blank=True, max_length=255, null=True)),
                ("price", models.IntegerField(blank=True, default=0, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                (
                    "_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "ladder",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.ladders",
                    ),
                ),
            ],
        ),
    ]
