# Generated by Django 6.0 on 2025-12-31 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ladders",
            name="shares_per_trade",
            field=models.DecimalField(
                blank=True, decimal_places=16, max_digits=20, null=True
            ),
        ),
    ]
