# Generated by Django 6.0 on 2026-01-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_ladders_shares_per_trade"),
    ]

    operations = [
        migrations.AddField(
            model_name="ladders",
            name="type",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
