# Generated by Django 6.0 on 2026-01-02 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_ladders_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("apt", models.IntegerField(blank=True, default=0, null=True)),
                ("order_id", models.IntegerField(blank=True, null=True)),
                (
                    "profit",
                    models.DecimalField(
                        blank=True, decimal_places=16, max_digits=20, null=True
                    ),
                ),
                ("step_code", models.CharField(blank=True, max_length=20, null=True)),
                ("symbol", models.CharField(blank=True, max_length=10, null=True)),
                ("buy_date", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "buy_fee",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("buy_id", models.CharField(blank=True, max_length=255, null=True)),
                ("buy_placed", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "buy_price",
                    models.DecimalField(
                        blank=True, decimal_places=16, max_digits=20, null=True
                    ),
                ),
                (
                    "buy_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("sell_date", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "sell_fee",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("sell_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "sell_placed",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sell_price",
                    models.DecimalField(
                        blank=True, decimal_places=16, max_digits=20, null=True
                    ),
                ),
                (
                    "sell_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "ladder",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.ladders",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="steps",
            name="transaction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.transactions",
            ),
        ),
    ]
