# Generated by Django 6.0 on 2026-01-02 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="steps",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.transactions",
            ),
        ),
    ]
