# Generated by Django 6.0 on 2026-01-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_steps_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ladders",
            name="last",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=7, null=True
            ),
        ),
    ]
