# Generated by Django 6.0 on 2026-01-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="steps",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=6, default=0, max_digits=7, null=True
            ),
        ),
    ]
