# Generated by Django 6.0 on 2026-01-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_steps_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="ladders",
            name="amount_per_trade",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="ladders",
            name="percent_per_trade",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
