# Generated by Django 6.0 on 2026-01-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_ladders_amount_per_trade_ladders_percent_per_trade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ladders",
            name="amount_per_trade",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
