# Generated by Django 6.0 on 2026-01-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_alter_ladders_amount_per_trade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="steps",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=6, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="buy_price",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=20, null=True
            ),
        ),
    ]
