# Generated by Django 6.0 on 2026-01-05 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_alter_steps_price_alter_transactions_buy_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactions",
            name="apt",
        ),
        migrations.RemoveField(
            model_name="transactions",
            name="step_code",
        ),
        migrations.AddField(
            model_name="transactions",
            name="shares_per_trade",
            field=models.DecimalField(
                blank=True, decimal_places=16, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="transactions",
            name="step",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="base.steps"
            ),
        ),
        migrations.AlterField(
            model_name="ladders",
            name="last",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=20, null=True
            ),
        ),
    ]
