# Generated by Django 6.0 on 2026-01-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_remove_transactions_apt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="order_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
