# Generated by Django 6.0 on 2026-01-05 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_alter_transactions_order_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactions",
            name="createdAt",
        ),
    ]
