# Generated by Django 6.0 on 2026-01-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_remove_transactions_createdat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="profit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="shares_per_trade",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=12, null=True
            ),
        ),
    ]
