# Generated by Django 6.0 on 2026-01-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0016_alter_transactions_profit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ladders",
            name="amount_per_trade",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ladders",
            name="cap",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ladders",
            name="cover",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ladders",
            name="gap",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ladders",
            name="highest",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ladders",
            name="last",
            field=models.DecimalField(
                blank=True, decimal_places=6, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ladders",
            name="lowest",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ladders",
            name="profit",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ladders",
            name="profit_per_trade",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ladders",
            name="shares_per_trade",
            field=models.DecimalField(
                blank=True, decimal_places=16, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ladders",
            name="stop_price_in_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="buy_price",
            field=models.DecimalField(
                blank=True, decimal_places=6, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="buy_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="profit",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="sell_fee",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="sell_price",
            field=models.DecimalField(
                blank=True, decimal_places=6, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="sell_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="shares_per_trade",
            field=models.DecimalField(
                blank=True, decimal_places=6, default=0, max_digits=12, null=True
            ),
        ),
    ]
