# Generated by Django 6.0 on 2026-01-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0017_alter_ladders_amount_per_trade_alter_ladders_cap_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactions",
            name="status",
            field=models.CharField(default="OPEN", max_length=10),
        ),
    ]
