# Generated by Django 6.0 on 2026-01-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0018_transactions_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="status",
            field=models.CharField(
                default="OPEN", help_text="Transaction status", max_length=10
            ),
        ),
    ]
