# Generated by Django 6.0 on 2026-01-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0020_apicredentials"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apicredentials",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="apicredentials",
            name="last_used",
        ),
        migrations.RemoveField(
            model_name="apicredentials",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="apicredentials",
            name="encrypted_credentials",
            field=models.TextField(default="123"),
        ),
        migrations.AlterField(
            model_name="apicredentials",
            name="platform",
            field=models.CharField(default="ADefaultPlatform", max_length=200),
        ),
    ]
