# Generated by Django 6.0 on 2026-01-10 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0021_remove_apicredentials_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Historical",
            fields=[
                ("symbol_name", models.TextField(blank=True, null=True)),
                ("symbol", models.TextField(blank=True, null=True)),
                ("date", models.TextField(blank=True, null=True)),
                (
                    "close",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=0,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=0,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "open",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=0,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=0,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                ("date", models.TextField(blank=True, null=True)),
                (
                    "debt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=0,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=0,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "daily_debt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=0,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "daily_profit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=0,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "ladder",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.ladders",
                    ),
                ),
            ],
        ),
    ]
