# Generated by Django 6.0 on 2026-01-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0022_historical_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="historical",
            name="low",
            field=models.DecimalField(
                blank=True, decimal_places=6, default=0, max_digits=20, null=True
            ),
        ),
    ]
