# Generated by Django 6.0 on 2026-01-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0023_historical_low"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ladders",
            name="lowest",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=1000000, max_digits=9, null=True
            ),
        ),
    ]
