# Generated by Django 6.0 on 2026-01-13 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0024_alter_ladders_lowest"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="steps",
            unique_together={("ladder", "step_code")},
        ),
    ]
