# Generated by Django 6.0 on 2026-01-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0025_alter_steps_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ladders",
            name="amount_per_trade",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
