# Generated by Django 6.0 on 2026-01-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0026_alter_ladders_amount_per_trade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ladders",
            name="percent_per_trade",
            field=models.DecimalField(
                blank=True, decimal_places=0, default=0, max_digits=2, null=True
            ),
        ),
    ]
