# Generated by Django 6.0 on 2026-01-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0027_alter_ladders_percent_per_trade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ladders",
            name="debt",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ladders",
            name="limit_price_in_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=0, default=0, max_digits=2, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ladders",
            name="stop_price_in_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=0, default=0, max_digits=2, null=True
            ),
        ),
    ]
