# Generated by Django 6.0 on 2026-01-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0029_increase_decimal_field_precision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ladders",
            name="highest",
            field=models.DecimalField(
                blank=True, decimal_places=6, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ladders",
            name="lowest",
            field=models.DecimalField(
                blank=True, decimal_places=6, default=1000000, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ladders",
            name="profit_per_trade",
            field=models.DecimalField(
                blank=True, decimal_places=6, default=0, max_digits=12, null=True
            ),
        ),
    ]
