# Generated by Django 6.0 on 2026-01-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0030_alter_ladders_highest_alter_ladders_lowest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ladders",
            name="percent_change_24h",
            field=models.DecimalField(
                blank=True, decimal_places=6, default=0, max_digits=20, null=True
            ),
        ),
    ]
