# Generated by Django 6.0 on 2026-02-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0031_ladders_percent_change_24h"),
    ]

    operations = [
        migrations.AddField(
            model_name="ladders",
            name="alert",
            field=models.TextField(blank=True, default=""),
        ),
    ]
