# Generated by Django 6.0 on 2026-02-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0032_ladders_alert"),
    ]

    operations = [
        migrations.AddField(
            model_name="ladders",
            name="buffer_52_week",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
