# Generated by Django 6.0 on 2026-03-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0033_ladders_buffer_52_week"),
    ]

    operations = [
        migrations.AddField(
            model_name="ladders",
            name="trending",
            field=models.CharField(
                choices=[("RUN_AWAY", "Run Away"), ("HOUR_24", "24 Hour")],
                default="RUN_AWAY",
                max_length=20,
            ),
        ),
    ]
