# Generated by Django 6.0 on 2026-04-21 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0034_ladders_trending"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyLadderSnapshot",
            fields=[
                (
                    "_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                (
                    "profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "debt",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("buy_count", models.PositiveIntegerField(default=0)),
                ("sell_count", models.PositiveIntegerField(default=0)),
                ("is_closed", models.BooleanField(default=False)),
                ("committed_at", models.DateTimeField(auto_now=True)),
                (
                    "ladder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_snapshots",
                        to="base.ladders",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month"],
                "unique_together": {("ladder", "year", "month")},
            },
        ),
    ]
