# Generated by Django 6.0 on 2026-05-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0036_monthlyusersnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="carrier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("att", "AT&T"),
                    ("verizon", "Verizon"),
                    ("tmobile", "T-Mobile"),
                    ("cricket", "Cricket"),
                    ("boost", "Boost"),
                    ("metropcs", "Metro by T-Mobile"),
                    ("uscellular", "US Cellular"),
                    ("googlefi", "Google Fi"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="monthly_report",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="notify_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="notify_sms",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="weekly_report",
            field=models.BooleanField(default=False),
        ),
    ]
