# Generated by Django 6.0 on 2026-05-03 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0037_profile_carrier_profile_monthly_report_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="carrier",
        ),
    ]
